---
- name: Install packages after verifying Machine.
  hosts: all
  tasks:
    - name: Install packages after verifying Machine.
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"


    - name: Install packages after verifying Machine.
      yum:
        name: nginx
        state: present
      when: ansible_distribution == "RedHat"



...
