---
- name: Example of Ansible Notify Handlers.
  hosts: all
  tasks:
    - name: Install Apache Web Server
      yum:
        name: httpd
        state: installed
      register: adc

    - debug:
        var: adc.rc
    
    - name: start apache
      service:
        name: httpd
        state: started
    - name: restart apache
      service: 
        name: httpd
        state: restarted
      when: adc.rc != '0'

...
