---
- name: Add user accounts from another PB
  hosts: all
  vars_files:
    - /home/tanjeel/Ansible/Playbooks/user_name_loop.yml
  tasks:

    - name: Adding user accounts from another PB
      user:
        name: "{{ item }}"
        state: absent
        groups: wheel

      with_items:
        "{{ users }}"

...

