---
- name: Take Input from User
  hosts: rhel8
  vars_prompt:
    - name: user_name
      prompt: user
      private: no

    - name: password
      prompt: password
      private: yes

  tasks:
    - debug:
        msg: "Your User: {{ user_name }}, Password: {{ password }}" 


...
