---
- name: Add single user into multiple groups
  hosts: all
  tasks:
    - name: Adding Groups
      group:
        name: "{{ item }}"
        state: present
      with_items:
        - school
        - student
        - teacher

    - name: Adding Users
      user:
        name: "{{ item[0] }}"
        state: present
        groups: "{{ item[1] }}"
        append: yes
      with_nested:
        - { amit, vikas, max, paul }
        - { school, student, teacher }

...
