---
- name: Install Yum packages
  hosts: all
  tasks:
    - name: Installing Packages
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - zsh
        - vsftpd
        - httpd 
        - ftp
        - wget



...
